name: CompFuzzy
on: [push, workflow_dispatch]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Fuzzer
        uses: actions/github-script@v7
        with:
            github-token: ${{ secrets.COMPFUZZCI_PAT }}
            script: |
              await github.rest.actions.createWorkflowDispatch({
                  owner: 'kbuaaaaaa',
                  repo: 'CompFuzzy',
                  workflow_id: 'fuzzer_build.yaml',
                  ref: 'main'
              })
  Fuzz:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Run Fuzzer
        uses: actions/github-script@v7
        with:
            github-token: ${{ secrets.COMPFUZZCI_PAT }}
            script: |
              await github.rest.actions.createWorkflowDispatch({
                  owner: 'kbuaaaaaa',
                  repo: 'CompFuzzy',
                  workflow_id: 'fuzzer_run.yaml',
                  ref: 'main'
              })
