name: Fuzzing on PR
on:
  pull_request_target:
    branches:
      - main
  
jobs:
  PrintInfo:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: |
          echo "${{github.event.pull_request}}"
        
