name: CompFuzzy
on: [push, workflow_dispatch]
jobs:
  Fuzz:
    runs-on: ubuntu-latest
    steps:
      - name: Build Fuzzer
        uses: kbuaaaaaa/CompFuzzy/.github/workflows/fuzzer_build
      - name: Run Fuzzer
        uses: kbuaaaaaa/CompFuzzy/.github/workflows/fuzzer_run
