name: CompFuzzy
on: [push, workflow_dispatch]
jobs:
  Fuzzing:
    runs-on: ubuntu-latest
    steps:
    - name: Build
      uses: kbuaaaaaa/CompFuzzy/fuzzer_build@main
      with:
          fuzzer: fuzz-d