name: CompFuzzy
on: [push, workflow_dispatch]
jobs:
  Fuzz:
    runs-on: ubuntu-latest
    steps:
      - name: Install Java 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Install Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.5
      - name: Clone fuzz-d
        uses: actions/checkout@master
        with:
          repository: kbuaaaaaa/fuzz-d
          submodules: recursive
      - name: Build fuzz-d
        run: |
          ./gradlew build --info
      - name: Install Dafny
        uses: dafny-lang/setup-dafny-action@v1
      - name: Run fuzz-d
        run: |
          java -jar /app/build/libs/app.jar fuzz
          cd output
          cat fuzz-d.log
    
          
      
