name: CompFuzzy
on: [push, workflow_dispatch]
jobs:
  Fuzz:
    runs-on: ubuntu-latest
    steps:
      - name: Build Fuzzer
        uses: actions/github-script@v7
        with:
            github-token: ${{ secrets.COMPFUZZY_PAT }}
            script: |
              await github.actions.createworkflowDispatch({
                  owner: 'kbuaaaaaa',
                  repo: 'CompFuzzy',
                  workflow_id: 'fuzzer_build.yaml',
                  ref: 'main'
              })
      - name: Run Fuzzer
        uses: actions/github-script@v7
        with:
            github-token: ${{ secrets.COMPFUZZY_PAT }}
            script: |
              await github.actions.createworkflowDispatch({
                  owner: 'kbuaaaaaa',
                  repo: 'CompFuzzy',
                  workflow_id: 'fuzzer_run.yaml',
                  ref: 'main'
              })
