name: CompFuzzy
on: [push, workflow_dispatch]
jobs:
  Fuzzing:
    runs-on: ubuntu-latest
    steps:
    - name: Build
      uses: kbuaaaaaa/compfuzzy/fuzzer_build
      with:
          fuzzer: fuzz-d