name: CompFuzzy
on: [push, workflow_dispatch]
jobs:
  Fuzz:
    runs-on: ubuntu-latest
    steps:
      - name: Build Fuzzer
        uses: kbuaaaaaa/CompFuzzy/fuzzer_build@main
      - name: Run Fuzzer
        uses: kbuaaaaaa/CompFuzzy/fuzzer_run@main
