name: CompFuzzy
on: [push, workflow_dispatch]
jobs:
  Build_Fuzzer:
    runs-on: ubuntu-latest
    steps:
      - name: Install Java 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Clone fuzz-d
        uses: actions/checkout@master
        with:
          repository: kbuaaaaaa/fuzz-d
      - name: Build fuzz-d
        run: |
          ls
          ./gradlew build --info
          
      
